services:
  - type: web
    name: taskmanagement
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate --noinput && \
      gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "0"
      - key: SQLITE_PATH
        value: "/var/data/db.sqlite3"
      # optional: allow any host; see step 2 for safer auto-host config
      - key: ALLOWED_HOSTS
        value: "*"
    disk:
      name: db
      mountPath: /var/data
      sizeGB: 1